server:
  port: 8019
#spring应用名字
spring:
  application:
    name: OrderConsumerApplication
#dubbo配置
dubbo:
  application:
    name: order-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: zk-registry
    address: zookeeper://192.168.5.130:2181?blockUntilConnectedWait=100000&timeout=100000
  config-center:
    address: zookeeper://192.168.5.130:2181
  metadata-report:
    address: zookeeper://192.168.5.130:2181